language: typescript
node_js:
- 6.11.4
before_install:
- npm install -g typescript@2.8.3
script:
- npm i
- npm test
deploy:
  provider: npm
  script:
  - npm run build
  email: vladimirdjukic90@gmail.com
  api_key: TOKEN
  on:
    tags: false
    repo: vforv/justinject
